#!/bin/bash
opp_runall -j3 opp_run -r 0..149 -u Cmdenv -n ../../..:../../../../examples:../../../../src -l ../../../../src/inet -l ../../../inet -c NoEpidemic  DtnTest.ini
opp_runall -j3 opp_run -r 0..49 -u Cmdenv -n ../../..:../../../../examples:../../../../src -l ../../../../src/inet -l ../../../inet -c Epidemic DtnTest.ini
