//
// Generated file, do not edit! Created by opp_msgc 4.3 from applications/dtn/msdp/MSDPDataMsg.msg.
//

#ifndef _MSDPDATAMSG_M_H_
#define _MSDPDATAMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/dtn/msdp/MSDPDataMsg.msg</tt> by opp_msgc.
 * <pre>
 * packet MSDPInfo{
 *     double DtnIndex;
 * }
 * </pre>
 */
class MSDPInfo : public ::cPacket
{
  protected:
    double DtnIndex_var;

  private:
    void copy(const MSDPInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MSDPInfo&);

  public:
    MSDPInfo(const char *name=NULL, int kind=0);
    MSDPInfo(const MSDPInfo& other);
    virtual ~MSDPInfo();
    MSDPInfo& operator=(const MSDPInfo& other);
    virtual MSDPInfo *dup() const {return new MSDPInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getDtnIndex() const;
    virtual void setDtnIndex(double DtnIndex);
};

inline void doPacking(cCommBuffer *b, MSDPInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MSDPInfo& obj) {obj.parsimUnpack(b);}


#endif // _MSDPDATAMSG_M_H_
